language: objective-c
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - APM_TEST_PACKAGES="tool-bar atom-toolbar-preferred"
  - secure: bWlN1W/MMRug5u3nTNMHEJjIodZFj0NFhnBruK1t7QX8vuA/Q0EuXbPTuvrGHZHChxpnyjUcgUYuIAIGveuDirfJw+9t46xZ0CWTb9Dzq3k0bcAOYVpSetJjv2e2xYB8WxZHX79ByYgldk1tT1NNvm8wNyOhRR+EDiQ/vLZC2oJHtaf49tpEGMSrhDS7jJz0jkxLe9nDIrf106FRMEnZu58s+fe5fVbxC/7kOFv4fHDzIPMwArJY1RRqX58N/1qn9d930QAHIlUeCLEQWMw+pd36pCj/0t4CNV//ZWtwCpVC/EVpDjVX+fyg2zL0Wy8couQLDTKAnIAA7BLiMknluimheqvvqVYho+ObIC8APxNZgGBJnONY3skZnI9rh7fc/KUVCPCK+WmbrPP7dlN/lNDGKz9OmlWiu/PYqB3f2v5ZHRZ1Uh9C3DdQLFb+aMb2NSvdUkrnsjeHvmRcixd+j9o1QUG/UL1kjaXIIuiLE7AfPo5n9gHqaJiU1K9QcBlSvfgx0cjOIrN3+k4k8veVp6YMRnnxjKQrPmo29qIHigzSmmWQwFxScMh8sfsBnoqjgs3cMxn11dd/ba/4pPcLPlFQy8pDkCrcV3tGKWsK/RRYLTBz72yKfXq4EFH8jKgrWFS9FDYOyZ0evLM2+lCHMt+ZECtlIKHD8ICfnYtMQog=
  matrix:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta
script:
- curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
- "./node_modules/.bin/remark ."
before_install: yarn global add greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
git:
  depth: 10
